import os

# CONFIGURATION
project_config = {
    "title": "Facebook: Real-Time Viral Content Detection",
    "problem_statement": (
        "With billions of posts daily, Facebook needs to instantly identify 'Viral' content "
        "to push it to users' News Feeds. Waiting for batch processing means missing the trend. "
        "We need a real-time stream processor to calculate 'Reaction Velocity'."
    ),
    "requirements": [
        "Ingestion: Handle bursty traffic (e.g., Live Events, Breaking News).",
        "Velocity Tracking: Calculate interactions per second for every Post ID.",
        "Thresholding: If velocity > 100/sec, flag as 'Viral'.",
        "Reaction Types: Distinguish between 'Like' (Positive) and 'Angry' (Controversial)."
    ],
    "pipeline_description": (
        "1. **Interaction Stream (Producer)**: Simulates user reactions (Like, Love, Angry).\n"
        "2. **Ingest**: Kafka Topic `fb-interactions`.\n"
        "3. **Velocity Engine (Consumer)**: \n"
        "   - Aggregates reactions in 2-second windows.\n"
        "   - Flags posts exceeding the 'Viral Threshold'.\n"
        "4. **Action**: Updates the Global Feed algorithm instantly."
    ),
    "instructions": "python producer.py"
}

def generate_readme():
    target_path = "/workspaces/Taashi_Github/Implementation Code/15_Streaming_Big_Data/06_Facebook_Data"
    os.makedirs(target_path, exist_ok=True)
    file_path = os.path.join(target_path, "README.md")
    
    req_list = "\n".join([f"- {req}" for req in project_config['requirements']])
    B_BASH = "```bash"
    B_END = "```"
    
    content = f"""
# {project_config['title']}

## 1. Problem Statement
{project_config['problem_statement']}

## 2. Requirements & KPIs
{req_list}

## 3. Architecture & Pipeline
{project_config['pipeline_description']}

---

## 4. Technical Implementation

### File Structure
- `producer.py`: Generates a high-velocity stream of Likes/Reactions.
- `consumer.py`: The Viral Engine. Detects spikes in post traffic.
- `utils_logger.py`: Logging config.

### How to Run this Demo

**Step 1: Install Dependencies**
{B_BASH}
pip install -r requirements.txt
{B_END}

**Step 2: Start the Viral Engine (Consumer)**
This service monitors the stream for trends.
{B_BASH}
python consumer.py
{B_END}
*It will start listening for engagement spikes...*

**Step 3: Start the Traffic Generator (Producer)**
This simulates millions of users clicking 'Like'.
{B_BASH}
{project_config['instructions']}
{B_END}

**Step 4: Observe Trends**
Watch the Consumer terminal. You will see:
- 📈 **Rising**: A post is gaining traction.
- 🚀 **VIRAL TREND DETECTED**: A post has exploded in popularity.

---
*Generated by Automation Script | {project_config['title']} Project*
"""
    with open(file_path, "w") as f:
        f.write(content.strip())
    print(f"✅ README successfully written to:\n   {file_path}")

if __name__ == "__main__":
    generate_readme()