"""
Code Tool — Sandboxed code execution for agents.

Provides a restricted execution environment for running Python code
generated by agents. Captures stdout, stderr, and return values.
Security: runs in a restricted namespace with limited builtins.
"""

import io
import sys
import traceback
from contextlib import redirect_stdout, redirect_stderr
from .tool_registry import ToolDefinition


SAFE_BUILTINS = {
    "abs", "all", "any", "bool", "dict", "enumerate", "filter",
    "float", "format", "frozenset", "hasattr", "hash", "int",
    "isinstance", "issubclass", "iter", "len", "list", "map",
    "max", "min", "next", "print", "range", "repr", "reversed",
    "round", "set", "slice", "sorted", "str", "sum", "tuple",
    "type", "zip",
}


def execute_code(code: str, timeout_hint: int = 30) -> dict:
    """
    Execute Python code in a restricted namespace.

    Returns a dict with stdout, stderr, result (last expression value),
    and success flag. The namespace is isolated from the host process.

    Note: timeout_hint is advisory only in this demo. In production,
    use subprocess with actual timeout enforcement.
    """
    safe_builtins = {k: __builtins__[k] if isinstance(__builtins__, dict)
                     else getattr(__builtins__, k)
                     for k in SAFE_BUILTINS
                     if (k in __builtins__ if isinstance(__builtins__, dict)
                         else hasattr(__builtins__, k))}

    namespace = {"__builtins__": safe_builtins}

    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()

    try:
        with redirect_stdout(stdout_capture), redirect_stderr(stderr_capture):
            exec(compile(code, "<agent_code>", "exec"), namespace)

        # Try to capture the last expression's value
        result = namespace.get("result", namespace.get("output", None))

        return {
            "success": True,
            "stdout": stdout_capture.getvalue(),
            "stderr": stderr_capture.getvalue(),
            "result": str(result) if result is not None else None,
        }
    except Exception as e:
        return {
            "success": False,
            "stdout": stdout_capture.getvalue(),
            "stderr": stderr_capture.getvalue(),
            "error": f"{type(e).__name__}: {e}",
            "traceback": traceback.format_exc(),
        }


def validate_code(code: str) -> dict:
    """
    Validate Python code without executing it.

    Checks syntax and reports any issues. Useful for the Reviewer
    agent to validate code before approving execution.
    """
    try:
        compile(code, "<validation>", "exec")
        return {"valid": True, "issues": []}
    except SyntaxError as e:
        return {
            "valid": False,
            "issues": [{
                "line": e.lineno,
                "offset": e.offset,
                "message": e.msg,
            }]
        }


def create_code_tools() -> list[ToolDefinition]:
    """Create code execution tools."""
    return [
        ToolDefinition(
            name="execute_code",
            description="Execute Python code in a sandboxed environment",
            input_schema={
                "type": "object",
                "properties": {
                    "code": {"type": "string", "description": "Python code to execute"},
                    "timeout_hint": {"type": "integer", "default": 30}
                },
                "required": ["code"]
            },
            handler=execute_code
        ),
        ToolDefinition(
            name="validate_code",
            description="Validate Python code syntax without executing",
            input_schema={
                "type": "object",
                "properties": {
                    "code": {"type": "string", "description": "Python code to validate"}
                },
                "required": ["code"]
            },
            handler=validate_code
        ),
    ]
