"""
Executor Agent — Performs actions (code generation, file operations).

The execution engine of the pipeline. Takes instructions from the
plan and research findings, then executes the actual work — writing
code, creating files, running analysis.
"""

from typing import Any
from .base_agent import BaseAgent


class ExecutorAgent(BaseAgent):
    """
    Executes task actions using code and file tools.

    Reads the plan and research context from shared state, then
    performs the specified action. In production, this agent would
    use an LLM to generate code. For demo, uses templates.
    """

    # Mock code templates for demo
    CODE_TEMPLATES = {
        "analyze": '''
# Analysis generated by Executor Agent
data = {data_summary}
findings = []
for key, value in data.items():
    if isinstance(value, (int, float)):
        findings.append(f"{{key}}: {{value}}")
result = "\\n".join(findings)
print(f"Analysis complete: {{len(findings)}} findings")
''',
        "report": '''
# Report generated by Executor Agent
sections = {sections}
report_lines = ["# Task Report", ""]
for section in sections:
    report_lines.append(f"## {{section['title']}}")
    report_lines.append(section.get("content", "No content"))
    report_lines.append("")
result = "\\n".join(report_lines)
print(f"Report generated: {{len(sections)}} sections")
''',
        "transform": '''
# Data transformation by Executor Agent
input_data = {input_data}
output = {{k: str(v).upper() for k, v in input_data.items()}}
result = output
print(f"Transformed {{len(output)}} items")
''',
    }

    def execute(self, task: dict[str, Any]) -> dict[str, Any]:
        """
        Execute the task action.

        Determines the action type, gathers context from state,
        and performs the work using available tools.
        """
        action = task.get("action", "execute")
        action_type = task.get("action_type", "analyze")
        description = task.get("description", "")
        output_path = task.get("output_path", None)

        # Gather context from shared state
        research = self.read_state("research_findings", [])
        plan = self.read_state("current_plan", {})

        execution_result = {
            "action": action,
            "action_type": action_type,
            "steps_completed": [],
            "artifacts": [],
        }

        # Step 1: Validate code if provided
        code = task.get("code")
        if code:
            validation = self.use_tool("validate_code", {"code": code})
            if validation.success and validation.output.get("valid"):
                execution_result["steps_completed"].append("code_validated")
            else:
                execution_result["validation_errors"] = validation.output
                return execution_result

        # Step 2: Execute code or use template
        if code:
            exec_result = self.use_tool("execute_code", {"code": code})
        else:
            # Use template based on action type
            template = self.CODE_TEMPLATES.get(action_type, self.CODE_TEMPLATES["analyze"])
            mock_code = template.format(
                data_summary=repr({"task": description, "context_docs": len(research)}),
                sections=repr([{"title": "Findings", "content": description}]),
                input_data=repr({"task": description}),
            )
            exec_result = self.use_tool("execute_code", {"code": mock_code})

        if exec_result.success:
            execution_result["steps_completed"].append("code_executed")
            execution_result["output"] = exec_result.output
        else:
            execution_result["execution_error"] = exec_result.error

        # Step 3: Write output to file if path specified
        if output_path and exec_result.success:
            output_content = exec_result.output.get("result", exec_result.output.get("stdout", ""))
            if output_content:
                write_result = self.use_tool("write_file", {
                    "path": output_path,
                    "content": str(output_content)
                })
                if write_result.success:
                    execution_result["artifacts"].append(output_path)
                    execution_result["steps_completed"].append("output_written")

        # Store results in state
        self.write_state("execution_result", execution_result)
        self.write_state("plan_status", "executed")

        return execution_result
